### ISSUE TITLE
does not work with react native 

### ISSUE THREAD

**Issue by Bhivin** [khanshamshad32/Carousel#2]
Error:undefined is not an object(evaluating '_mathjs.default.cos')
Development environment;

 OS: Linux 3.19 Ubuntu 14.04.3 LTS, Trusty Tahr
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 1.11 GB / 7.68 GB
    Shell: 4.3.11 - /bin/bash
  Binaries:
    Node: 9.8.0 - /usr/local/bin/node
    npm: 6.4.0 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 23.0.1, 23.0.3, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.0, 27.0.2, 27.0.3, 28.0.3
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-rename: 2.3.2
    react-native-youtube: 2.0.0-beta.2

**Comment by cyb3rsalih** [comment]
did you install math.js `yarn add mathjs` or `npm install mathjs` ?

**Comment by Hosam-hsm** [comment]
not working

**Comment by mcfliermeyer** [comment]
I had to destructur the methods from mathjs for some reason. so my my import was: import { cos, sin, pi, abs } from 'mathjs'   and after that of course go remove all the references to Math.cos, Math.sin, ect...
But now it seems to work now

**Comment by khanshamshad32** [comment]
removed math.js dependency. Its should be working fine now. 
Closing this issue.
