### ISSUE TITLE
Duplicated files or mocks.

### ISSUE THREAD

**Issue by ThuyDang88** [khanshamshad32/Carousel#7]
I got this bug after  run npm install @khanshamshad32/carousel

  mockPath1:
   'node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json',
  mockPath2:
   'node_modules/@khanshamshad32/carousel/node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json' }

How can I fix it?

**Comment by khanshamshad32** [comment]
delete the directory 
node_modules/@khanshamshad32/carousel/node_modules.

The issue is showing because there are multiple react-native packages in your project.
